version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_PASSWORD: c85e70576d732df2062324adc69dec40
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_container
    command: redis-server --requirepass c85e70576d732df2062324adc69dec40
    ports:
      - "6379:6379"

volumes:
  postgres_data:
